#
# public.ecr.aws/docker/library/ubuntu:20.04
#
# FROM ubuntu:20.04
FROM public.ecr.aws/ubuntu/ubuntu:20.04_stable

RUN apt update
RUN apt-get install \
    git \
    vim \
    -y
RUN apt-get update && apt-get upgrade

# COPY

# CMD